workflows:
  ios-build:
    name: Oracle AI iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    integrations:
      app_store_connect: Oracle AI ASC
    
    environment:
      xcode: 15.4
      node: 20
      vars:
        BUNDLE_ID: com.oracleai.app
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install dependencies
        script: npm ci
        
      - name: Sync Capacitor
        script: npx cap sync ios
        
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          
      - name: Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
