workflows:
  ios-app:
    name: Oracle AI iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.oracleai.app
      xcode: latest
      node: 20
      vars:
        BUNDLE_ID: com.oracleai.app
    
    scripts:
      - name: Install Node dependencies
        script: npm install
        
      - name: Prepare web assets
        script: |
          mkdir -p ios/App/App/public
          cp -r public/* ios/App/App/public/ || true
        
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update || pod install
          
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
          
      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
    
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/*.ipa
      - "**/*.ipa"
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
