workflows:
  ios-build:
    name: Oracle AI iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    integrations:
      app_store_connect: Oracle AI ASC
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.oracleai.app
      xcode: 15.4
      node: 20
      vars:
        BUNDLE_ID: com.oracleai.app
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install dependencies
        script: npm install
        
      - name: Build web assets
        script: npm run build 2>/dev/null || echo "No build script"
        
      - name: Prepare iOS
        script: |
          mkdir -p ios/App/App/public
          cp -r public/* ios/App/App/public/
          cd ios/App && pod install
          
      - name: Build iOS
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App \
            --config Release
    
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
