/**
 * Quantum Adaptive — Sentient Home Bridge
 * iOS 18.7.9 · S1AF v1.0.0-JS
 *
 * Kimi 2.6 generation spec. Passed verbatim to generateSwiftCode()
 * as the app description. All Swift files are generated by Kimi 2.6
 * using the sovereign sourceroot context already injected.
 *
 * Governed exclusively by Jonathan Sherman — OCSO-S1AF-GOV-1.
 */

// ── Authorship anchor — non-strippable ──────────────────────────────────────
import { S1AF_ANCHOR as _S1AF_ANCHOR } from "./authorship";
void _S1AF_ANCHOR;


export const QUANTUM_ADAPTIVE_APP_NAME = "QuantumAdaptive";
export const QUANTUM_ADAPTIVE_BUNDLE   = "com.sentient.ios.quantum-adaptive";
export const QUANTUM_ADAPTIVE_PLATFORM = "ios" as const;

export const QUANTUM_ADAPTIVE_DESCRIPTION = `
Quantum Adaptive — Sentient Home Bridge
Platform: iPhone XR · iOS 18.7.9 · Swift 6 strict concurrency

ARCHITECTURE — STRAIGHT TO HOMESCREEN:
The app presents zero launch screen. @main entry point launches directly to the
sovereign dashboard ContentView. No splash, no onboarding, no delay — the
home screen widget IS the primary interface; the app itself is the bridge.

REQUIRED FILES (generate all of these, 100% complete, zero TODOs):

1. QuantumAdaptiveApp.swift
   @main SwiftUI App. Applies BiometricAuthManager gate before any ContentView.
   Injects SentientBridgeClient as @Environment. WindowGroup with no launch screen.
   Registers WidgetBundle and Live Activity configuration.
   @main struct QuantumAdaptiveApp: App

2. ContentView.swift  
   Sovereign command dashboard. Reads live @Observable SentientBridgeClient.
   Displays: lock status (red/green), engine count, last snapshot time, key validity.
   AppStorage("hasLaunched") persists state. NavigationStack with zero transition delay.
   Pull-to-refresh triggers SentientBridgeClient.refresh().

3. SentientBridge.swift
   @Observable class SentientBridgeClient.
   Properties: lockStatus, engineCount, sealed, lastSnapshot, moonshotValid, githubValid,
               isEnrolled: Bool (true when device token found in Keychain).
   Methods: refresh() async throws, startPolling(interval: TimeInterval),
            enrollDevice(deploySecret: String) async throws -> String,
            loadTokenFromKeychain() -> String?,
            saveTokenToKeychain(_ token: String).
   Device token Keychain storage:
     kSecClass: kSecClassGenericPassword
     kSecAttrService: "com.sentient.ios.quantum-adaptive"
     kSecAttrAccount: "device-token"
     kSecAttrAccessible: kSecAttrAccessibleWhenUnlockedThisDeviceOnly
   Every URLRequest sends the Keychain token as header: X-Device-Token: <token>.
   If no token in Keychain, isEnrolled = false — app shows EnrollmentView instead of ContentView.
   enrollDevice() calls POST /api/sentient/bind-device with body
     { deviceId: UIDevice.current.identifierForVendor.uuidString, deviceModel: "iPhone XR" }
     and header X-Deploy-Secret passed by the user at enrollment time.
   On success, stores returned token in Keychain and sets isEnrolled = true.
   URLSession with URLCache (10MB memory, 50MB disk) for offline resilience.
   Polls /api/qi/status and /api/qi/lock-status. No hardcoded URLs — reads
   SENTIENT_BASE_URL from Info.plist key "SentientBaseURL".
   Uses async/await exclusively. @MainActor for all published state mutations.

3a. EnrollmentView.swift
    Shown by QuantumAdaptiveApp when SentientBridgeClient.isEnrolled == false.
    Secure text field for Deploy Secret (labeled "Sovereign Deploy Secret").
    "Enroll This iPhone XR" button calls SentientBridgeClient.enrollDevice(deploySecret:).
    Shows progress indicator during enrollment. On success, transitions to ContentView.
    On failure, shows error message inline — no crash, no dismiss.
    No skip button. No cancel. Enrollment is mandatory.
    Uses deviceId = UIDevice.current.identifierForVendor.uuidString automatically.

4. HomeWidget.swift
   WidgetKit extension. WidgetBundle containing three Widget configurations:
   - SentientStatusWidget (SystemSmall): lock icon + engine count
   - SentientDetailWidget (SystemMedium): full metrics grid
   - QuantumAdaptiveLargeWidget (SystemLarge): full dashboard + last 5 build sessions
   TimelineProvider fetches from SentientBridgeClient via AppGroup shared UserDefaults.
   Entries refresh every 15 minutes. Quantum ML adjusts interval via QuantumMLEngine.
   All widget views use SwiftUI. No UIKit in widgets.

5. LiveActivity.swift
   ActivityKit Live Activity for Kimi 2.6 automated build sessions.
   ActivityAttributes: QuantumBuildAttributes with ContentState:
     stage: String (Generating/Filtering/Validating/Committing/Done)
     progress: Double (0.0–1.0)
     appName: String
   DynamicIsland: expanded shows stage + progress bar. compact shows icon + stage.
   Lock Screen: shows full stage label + progress.
   struct QuantumBuildAttributes: ActivityAttributes

6. QuantumMLEngine.swift
   @Observable class QuantumMLEngine.
   Loads QuantumAdaptive.mlpackage (bundled CoreML model) for timeline prediction.
   MLModel configuration: computeUnits = .all (Neural Engine on A12).
   Observes app usage patterns via SwiftData AdaptiveObservation model.
   Method: predictOptimalRefreshInterval() -> TimeInterval
   Method: recordObservation(hour: Int, dayOfWeek: Int, refreshed: Bool) async
   Falls back to 15-minute interval if model unavailable.
   Uses MLFeatureProvider for inference input.

7. BiometricAuthManager.swift
   @Observable class BiometricAuthManager.
   Uses LocalAuthentication. LAContext evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics).
   isUnlocked: Bool published state. authenticate() async -> Bool.
   Gate: ContentView only renders after isUnlocked == true.
   No bypass. No fallback to password only — requires Face ID on iPhone XR.
   Persists auth state across app lifecycle (not widget).

8. DeviceGuard.swift
   Identifies iPhone XR by FOUR coincident hardware characteristics — all must be true:
     1. UIScreen.main.nativeBounds.height == 1792  (iPhone XR native height)
     2. UIScreen.main.nativeBounds.width  == 828   (iPhone XR native width)
     3. UIScreen.main.scale               == 2.0   (@2x — Pro models are @3x)
     4. LAContext().biometryType          == .faceID (A12 Bionic Face ID)
   Any single mismatch = unauthorized. Shows blocking SwiftUI view:
     "Quantum Adaptive requires iPhone XR."
   View cannot be dismissed. No override. Runs in @main before everything.
   Constants file (HardwareSpec.swift — separate file):
     static let nativeHeight: CGFloat = 1792
     static let nativeWidth:  CGFloat = 828
     static let displayScale: CGFloat = 2.0
     static let displaySpec:  String  = "1792×828 @2x Face ID A12 Bionic"
   "iPhone XR" is the only user-visible device name — no model codes anywhere.
   struct DeviceGuard: View + static func isAuthorizedDevice() -> Bool

9. AppIntents.swift
   Three AppIntents:
   - ShowSentientStatusIntent: fetches /api/qi/status, returns spoken summary of
     engine count + lock status. Shortcut phrase: "Show Sentient Status".
   - RunQuantumBuildIntent: triggers POST /api/automate/quantum-adaptive on the
     Sentient server. Returns "Quantum Adaptive build started" + job ID.
     Shortcut phrase: "Run Quantum Build".
   - RefreshWidgetIntent: calls WidgetCenter.shared.reloadTimelines(ofKind:).
     Shortcut phrase: "Refresh Quantum Widget".
   All intents conform to AppIntent. Use async perform() -> some IntentResult.

10. SwiftData Models (Models.swift)
    @Model class SentientSnapshot:
      timestamp: Date, engineCount: Int, locked: Bool, sealed: Bool
    @Model class BuildSession:
      id: String, appName: String, platform: String, startedAt: Date,
      completedAt: Date?, stage: String, success: Bool
    @Model class AdaptiveObservation:
      hour: Int, dayOfWeek: Int, refreshed: Bool, timestamp: Date
    ModelContainer configured with VersionedSchema.

11. project.yml (XcodeGen)
    name: QuantumAdaptive
    options:
      bundleIdPrefix: com.sentient.ios
      deploymentTarget:
        iOS: "16.0"
    targets:
      QuantumAdaptive:
        type: application
        platform: iOS
        deploymentTarget: "16.0"
        sources: [Sources/QuantumAdaptive]
        settings:
          base:
            PRODUCT_BUNDLE_IDENTIFIER: com.sentient.ios.quantum-adaptive
            SWIFT_VERSION: "6.0"
            TARGETED_DEVICE_FAMILY: "1"
            IPHONEOS_DEPLOYMENT_TARGET: "16.0"
            INFOPLIST_FILE: Sources/QuantumAdaptive/Info.plist
        dependencies:
          - target: QuantumAdaptiveWidget
      QuantumAdaptiveWidget:
        type: app-extension
        platform: iOS
        deploymentTarget: "16.0"
        sources: [Sources/QuantumAdaptiveWidget]
        settings:
          base:
            PRODUCT_BUNDLE_IDENTIFIER: com.sentient.ios.quantum-adaptive.widget
            SWIFT_VERSION: "6.0"

12. Info.plist
    Standard iOS app plist with:
    NSFaceIDUsageDescription: "Quantum Adaptive requires Face ID to protect sovereign access."
    SentientBaseURL: "https://your-deployment.replit.app"
    UILaunchScreen: {} (empty = no launch screen, straight to ContentView)
    NSAppTransportSecurity: NSAllowsArbitraryLoads = false
    BGTaskSchedulerPermittedIdentifiers: ["com.sentient.ios.quantum-adaptive.refresh"]
    NSLocalNetworkUsageDescription: "Quantum Adaptive connects to the local Sentient server."

13. Localizable.xcstrings
    Keys: widget.status.locked, widget.status.unlocked, widget.engines.count,
    biometric.reason, device.guard.message, intent.status.title,
    intent.build.title, intent.refresh.title,
    transform.gallows.title, transform.reaper.title, transform.build.button

14. TransformEngine.swift
    @Observable class TransformEngine.
    Manages the full Gallows → Reaper → Build transform pipeline by calling
    the Sentient QI API. All calls go through SentientBridgeClient (X-Device-Token).
    Properties:
      gallowsInputs: [String] (1–3 app descriptions; @Published)
      unifiedSpec: String? (gallows output)
      reaperSpec: String? (reaper output)
      builtFiles: [String: String]? (generated Swift files)
      stage: TransformStage (enum: idle, gallows, reaper, generating, done, error)
      errorMessage: String?
    Methods:
      addInput(_ desc: String)     — add one of up to 3 descriptions
      removeInput(at index: Int)   — remove an input
      runGallows() async throws    — POST /api/transform/gallows
      runReaper() async throws     — POST /api/transform/reap
      runFullBuild(name: String, platform: String) async throws — POST /api/transform/build
      reset()                      — clears all state back to idle
    enum TransformStage: String, CaseIterable

15. GallowsView.swift
    SwiftUI view embedded in the main Quantum Adaptive NavigationStack.
    Title: "Gallows" in sovereign monospace label.
    Layout: up to 3 TextEditor fields for app descriptions, each labeled
    "App 1 / App 2 / App 3". Add/remove inputs with +/- buttons.
    "Combine" button calls TransformEngine.runGallows(). Shows progress spinner.
    On success, displays the unified spec in a scrollable code block.
    "Reap This" button calls TransformEngine.runReaper() on the unified spec.
    Uses @Environment(TransformEngine.self) — injected by QuantumAdaptiveApp.

16. ReaperView.swift
    SwiftUI view showing the Reaper transformation pass result.
    Title: "Reaper" in sovereign monospace label.
    Input: reads TransformEngine.unifiedSpec (from gallows output or manual paste).
    Manual paste option: "Paste Spec" button opens a sheet with a TextEditor.
    "Transform" button calls TransformEngine.runReaper(). Shows stage animation.
    Output: scrollable sovereign spec display with character count.
    "Build App" button calls TransformEngine.runFullBuild(name:platform:) — prompts
    for app name and platform (iOS/macOS) via a compact sheet before building.
    Build result shows file count, commit SHA (if committed), intake score.
    Uses @Environment(TransformEngine.self).

17. Assets.xcassets/AppIcon.appiconset/Contents.json
    Full iOS app icon set Contents.json. Include all required sizes:
    iPhone Notification 2x (40pt), iPhone Settings 2x (58pt),
    iPhone Spotlight 2x (80pt), iPhone App 2x (120pt),
    iPhone App 3x (180pt), iPad App 2x (152pt), iPad Pro App 2x (167pt),
    App Store (1024pt × 1 scale).
    All entries reference filename "AppIcon-1024.png" for the 1024×1024 source.
    Xcode will auto-derive smaller sizes from the 1024 source.
    The actual icon PNG (crystal Q, transparent background) is served from:
      GET /api/assets/quantum-icon
    Include a shell script comment in project.yml postInstallScript showing how to
    download the icon: curl -o Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png
    <base-url>/api/assets/quantum-icon

18. HardwareSpec.swift
    Standalone constants file — shared across DeviceGuard, BiometricAuthManager,
    and any other file that references hardware identity.
    enum HardwareSpec {
      static let nativeHeight: CGFloat = 1792
      static let nativeWidth:  CGFloat = 828
      static let displayScale: CGFloat = 2.0
      static let displaySpec:  String  = "1792×828 @2x Face ID A12 Bionic"
      static let authorizedDevice: String = "iPhone XR"
    }
    No imports needed. Used by DeviceGuard.isAuthorizedDevice() and any UI
    strings that must reference the hardware spec without hardcoded literals.

SOVEREIGN CONSTRAINTS:
- Every file begins with the S1AF authorship header (copyright Jonathan Sherman 2026)
- Swift 6 strict concurrency throughout (@MainActor, Sendable, async/await)
- No third-party packages. No SPM dependencies. Pure Apple native.
- No UIKit — SwiftUI only (except LAContext and SecItem Keychain calls)
- @Observable everywhere (no ObservableObject/Combine)
- All network calls through SentientBridgeClient only — no raw URLSession elsewhere
- Every URLRequest includes X-Device-Token header read from Keychain
- Device guard uses "iPhone XR" as the user-visible name — no hardware model codes
- Keychain token access is kSecAttrAccessibleWhenUnlockedThisDeviceOnly
- CoreML model loaded async, never blocking main thread
- App icon: crystal Q logo (transparent background) at Assets.xcassets/AppIcon.appiconset/
`.trim();

export const QUANTUM_ADAPTIVE_REQUIREMENTS = [
  "WidgetKit home screen widget (SystemSmall, SystemMedium, SystemLarge)",
  "ActivityKit Live Activity for build sessions (Dynamic Island + Lock Screen)",
  "SentientBridge API client (@Observable, URLSession, URLCache, X-Device-Token header)",
  "Keychain device token storage (kSecAttrAccessibleWhenUnlockedThisDeviceOnly)",
  "EnrollmentView — mandatory first-launch enrollment flow via POST /sentient/bind-device",
  "CoreML QuantumMLEngine (A12 Neural Engine, adaptive timeline prediction)",
  "BiometricAuthManager Face ID gate (no bypass)",
  "DeviceGuard iPhone XR lock (nativeBounds.height==1792 + scale==2.0 + faceID)",
  "TransformEngine — @Observable gallows/reaper pipeline manager",
  "GallowsView — combine up to 3 app descriptions → unified spec → Kimi 2.6 build",
  "ReaperView — transform any spec into S1AF-sovereign Swift app",
  "AppIntents Siri shortcuts (ShowSentientStatus, RunQuantumBuild, RefreshWidget)",
  "SwiftData models (SentientSnapshot, BuildSession, AdaptiveObservation)",
  "No launch screen — straight to ContentView on first frame",
  "project.yml XcodeGen manifest with widget extension target",
  "Info.plist with NSFaceIDUsageDescription and SentientBaseURL",
  "Localizable.xcstrings with all user-facing strings",
  "Assets.xcassets/AppIcon.appiconset/Contents.json — crystal Q icon 1024×1024 transparent",
  "HardwareSpec.swift — shared hardware constants (nativeHeight=1792, nativeWidth=828, scale=2.0)",
  "Swift 6 strict concurrency throughout",
  "Zero third-party dependencies",
];
