#!/bin/bash
# Q++RS Automated iOS Build Script
# Generated by Q++RS Code Studio

set -e

echo "=========================================="
echo "  Oracle AI - iOS Cloud Build"
echo "  Powered by Q++RS Ultimate 5.0"
echo "=========================================="

# Sync latest web assets
npx cap sync ios

# Install CocoaPods dependencies
cd ios/App
pod install --repo-update

# Build for Release
xcodebuild -workspace App.xcworkspace \
  -scheme App \
  -configuration Release \
  -destination 'generic/platform=iOS' \
  -archivePath build/OracleAI.xcarchive \
  archive

# Export IPA
xcodebuild -exportArchive \
  -archivePath build/OracleAI.xcarchive \
  -exportPath build/OracleAI \
  -exportOptionsPlist ExportOptions.plist

echo "=========================================="
echo "  Build Complete: build/OracleAI/Oracle AI.ipa"
echo "=========================================="
