#!/bin/bash
echo "═══════════════════════════════════════════════════════════"
echo "  Oracle AI - Apple App Store Connect Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Opening Apple Developer Portal..."
echo ""
echo "https://appstoreconnect.apple.com/access/integrations/api"
echo ""
echo "Steps:"
echo "  1. Sign in with Apple ID"
echo "  2. Click 'Generate API Key' or '+'"
echo "  3. Name: 'Oracle AI'"
echo "  4. Access: 'App Manager'"
echo "  5. Click 'Generate'"
echo "  6. Download .p8 file"
echo "  7. Copy Key ID and Issuer ID"
echo ""
echo "After download, run:"
echo "  ./scripts/configure-apple.sh <key_id> <issuer_id> <path_to_p8>"
echo ""
